version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=proshop
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=proshop
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
