export const PRODCUT_LIST_REQUEST = "PRODCUT_LIST_REQUEST";
export const PRODCUT_LIST_SUCCESS = "PRODCUT_LIST_SUCCESS";
export const PRODCUT_LIST_FAIL = "PRODCUT_LIST_FAIL";

export const PRODCUT_DETAILS_REQUEST = "PRODCUT_DETAILS_REQUEST";
export const PRODCUT_DETAILS_SUCCESS = "PRODCUT_DETAILS_SUCCESS";
export const PRODCUT_DETAILS_FAIL = "PRODCUT_DETAILS_FAIL";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
